name: stop functionapp

on: workflow_dispatch

jobs:
  start-functionapp:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionapp stop --name wecom-bot --resource-group wecom-bot